/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panels;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import fashion.store.management.system.Apparel;
import fashion.store.management.system.Customer;
import fashion.store.management.system.Validation;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.print.Printer;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ReturnItem extends javax.swing.JPanel {

    /**
     * Creates new form ReturnItem
     */
    //static int count =0;
    private ArrayList<Integer> Clothes_Count = new ArrayList<Integer>();
    private ArrayList<Integer> Clothes_CountReturn = new ArrayList<Integer>();
    private ArrayList<String> Clothes_NameRemoveReturn = new ArrayList<String>();
    private ArrayList<Integer> Clothes_CountRemoveReturn = new ArrayList<Integer>();
    
    public ReturnItem() {
        initComponents();
        jPanelSearchKey.setVisible(false);
    }
    private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelSuccessOrFail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jSpinnerRemove = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldSalary = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxItems = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAddListQuantity = new javax.swing.JTextField();
        jPanelSearchKey = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(105, 105, 105));

        jTextFieldName.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Retrive Clothes ...!");

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock ID", "Category Name", "Type", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity");

        jSpinnerRemove.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N

        jTextFieldSalary.setEditable(false);
        jTextFieldSalary.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jTextFieldSalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salary");

        jComboBoxItems.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Items");

        jTextFieldAddListQuantity.setEditable(false);
        jTextFieldAddListQuantity.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldAddListQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAddListQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddListQuantityActionPerformed(evt);
            }
        });

        jPanelSearchKey.setBackground(new java.awt.Color(105, 105, 105));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel12.setText("Wrong Search Key");

        javax.swing.GroupLayout jPanelSearchKeyLayout = new javax.swing.GroupLayout(jPanelSearchKey);
        jPanelSearchKey.setLayout(jPanelSearchKeyLayout);
        jPanelSearchKeyLayout.setHorizontalGroup(
            jPanelSearchKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchKeyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSearchKeyLayout.setVerticalGroup(
            jPanelSearchKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchKeyLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(105, 105, 105));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Find_and_Replace_96px.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(105, 105, 105));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(105, 105, 105));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Return_96px.png"))); // NOI18N
        jLabel13.setText("Retrive");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(105, 105, 105));

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Minus_35px.png"))); // NOI18N
        jLabel14.setText("Decrease Quantity");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel14))
        );

        jPanel6.setBackground(new java.awt.Color(105, 105, 105));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Clear_Symbol_35px.png"))); // NOI18N
        jLabel5.setText("Remove Item");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(241, 241, 241)
                                        .addComponent(jPanelSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxItems, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAddListQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jSpinnerRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSuccessOrFail)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldAddListQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jSpinnerRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void setComboBox(Customer c)
    {

        for(int i=0;i<c.getClothes().size();i++)
        {
            jComboBoxItems.addItem(c.getClothes().get(i));
        }
    }
    
    private void setTable(Customer c)
     {
         resetTable();
         ArrayList<Apparel> arr = new ArrayList<Apparel>();
         Apparel re = new Apparel();
         for(int i=0;i<c.getClothes().size();i++)
             arr.add(re.returnInfoItem(Integer.parseInt(c.getClothes().get(i))));
         
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[5];
        
        for(int i=0;i<arr.size();i++)
        {
            rowData [0]=arr.get(i).getStockID();
            rowData [1]=arr.get(i).getNameofCategory();
            rowData [2]=arr.get(i).getType();
            rowData [3]=arr.get(i).Calc_Item(arr.get(i).getStockID(),c.getClothes_No().get(i));
            rowData [4]=c.getClothes_No().get(i);
            model.addRow(rowData);
        }
    }
    
    private void resetTable()
     {
         try{
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            while(jTable1.getRowCount()>0){
                for(int i=0;i<jTable1.getRowCount();i++)
                    model.removeRow(i);
            }
            model.removeRow(0);
        }
        catch(Exception e)
        {
            ;
        }
     }
    private void printer(Customer c)
    {
            Document doc = new Document();
            try {
                try {
                    String path = jTextFieldName.getText()+" Report.pdf";
                    PdfWriter.getInstance(doc, new FileOutputStream(path));
                    System.out.println("Create Pdf :)");
                    } catch (FileNotFoundException ex) {
                    Logger.getLogger(Printer.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("problem in printing : Youssef");
                    }
                    doc.open();
                    Apparel a = new Apparel();
                    String sepreted[]=jComboBoxItems.getSelectedObjects().toString().split(" ");
                    System.out.println(" Done !");
                    doc.add(new Paragraph("Name of Customer : "+c.getName() +",              Email : "+c.getEmail()+"\nPhone No : "+c.getPhoneNo()+"\n\n"));
                    ArrayList<String> NameClothes = c.getClothes();
                    for(int i=0;i<Clothes_Count.size();i++){
                        doc.add(new Paragraph("Name "+NameClothes.get(i) + ",         Quantity : "+Clothes_Count.get(i)+",           Salary : "
                                               +a.Calc_Item(Integer.parseInt(NameClothes.get(i)), Clothes_Count.get(i))));
                    }
                        doc.add(new Paragraph("\n-------------------------------------------------------"
                                + "\n                    Total : "+c.getPrice()));
                    doc.addTitle("Billing ...!");
                    doc.addAuthor("Manager: Youssef F.Rashad");
                    doc.addCreationDate();
                    jLabelSuccessOrFail.setText(" Done ... !");
                    doc.close();
            } catch (DocumentException ex) {
                System.out.println("problem in printing : Youssef");
                Logger.getLogger(Printer.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    private void resetPanel()
    {
        jSpinnerRemove.setEnabled(false);
        jComboBoxItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jSpinnerRemove.setValue(0);
        jTextFieldAddListQuantity.setText("");
        Clothes_Count = new ArrayList<Integer>();
        Clothes_CountRemoveReturn = new ArrayList<Integer>();
        Clothes_CountReturn = new ArrayList<Integer>();
        Clothes_NameRemoveReturn = new ArrayList<String>();
        resetTable();
        
        jPanelSearchKey.setVisible(false);
        
    }
    private void jTextFieldSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaryActionPerformed

    private void jTextFieldAddListQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddListQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddListQuantityActionPerformed

    private void jComboBoxItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemsActionPerformed
        // TODO add your handling code here:
        try{
        if(Clothes_Count.size()!=0)
            jTextFieldAddListQuantity.setText(""+Clothes_Count.get(jComboBoxItems.getSelectedIndex()));
        }
        catch(Exception e){
            ;
        }
    }//GEN-LAST:event_jComboBoxItemsActionPerformed

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        resetPanel();
        jComboBoxItems.removeAllItems();
        if(!jTextFieldName.getText().equals("")){
            if(new Validation().checkName(jTextFieldName.getText())){
                Customer c = new Customer();
                c = c.getCustomer(jTextFieldName.getText());
                if(c!=null){
                    jSpinnerRemove.setEnabled(true);
                    Clothes_Count  = c.getClothes_No();
                    int size = c.getClothes_No().size();
                    for(int i=0;i<size;i++)// 34an dh elly hyzod el No of Clothes flma yb2 b 0 hdyf el zyada w yzod 3lyh
                        Clothes_CountReturn.add(0);
                    setComboBox(c);
                    setTable(c);
                    jLabelSuccessOrFail.setText("Founded Customer ;)");
                }
                else{
                    jLabelSuccessOrFail.setText("Not Found Customer  :(");
                    JOptionPane.showMessageDialog(null, "Not Found Customer Try Again :(");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid Name Try Again :(");
                jPanelSearchKey.setVisible(true);
            }
            
        }
        else
        jLabelSuccessOrFail.setText("Missing Required Name of Customer ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        jLabelSuccessOrFail.setText("Retrive Clothes ...!");
        jTextFieldSalary.setText("");
        jTextFieldName.setText("");
        resetPanel();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        if(!jTextFieldName.getText().equals("")){
            if(jTable1.getRowCount()!=0){
                    Customer c = new Customer();
                    c = c.getCustomer(jTextFieldName.getText());
                    if(c!=null){
                        c.removeAllClothesAndNo();
                        int StockID[] = new int[jComboBoxItems.getItemCount()];
                        int Count_Quantity[] = new int[jComboBoxItems.getItemCount()];
                        c.Clothes = new ArrayList<String>();
                        c.Clothes_No = new ArrayList<Integer>();
                        for(int i=0;i<jComboBoxItems.getItemCount();i++){
                            c.setClothes(jComboBoxItems.getItemAt(i));
                            c.setClothes_No(Clothes_Count.get(i));
                            StockID[i]=Integer.parseInt(jComboBoxItems.getItemAt(i));
                            Count_Quantity[i]=(Clothes_Count.get(i));
                        }
                        c.setPrice(new Apparel().Calc_Total(StockID, Count_Quantity));
                       
                        int []arrReturn = new int[Clothes_CountReturn.size()];
                        int []StockIDRemoveReturn = new int[Clothes_NameRemoveReturn.size()];
                        int []CountRemoveReturn = new int[Clothes_CountRemoveReturn.size()];
                        for(int i=0;i<Clothes_CountReturn.size();i++)
                            arrReturn[i]=Clothes_CountReturn.get(i);
                        for(int i=0;i<Clothes_NameRemoveReturn.size();i++)
                            StockIDRemoveReturn[i]=Integer.parseInt(Clothes_NameRemoveReturn.get(i));
                        for(int i=0;i<Clothes_CountRemoveReturn.size();i++)
                            CountRemoveReturn[i]=Clothes_CountRemoveReturn.get(i);
                        
                        System.err.println(Arrays.toString(arrReturn)+"\t"+Clothes_CountReturn.toString());
                        if(new Apparel().specificQuantityInc(StockID, arrReturn)&&new Apparel().specificQuantityInc(StockIDRemoveReturn,CountRemoveReturn)){
                            if(c.editInCustomer(jTextFieldName.getText())){
                                printer(c);
                                jTextFieldSalary.setText(""+new Apparel().Calc_Total(StockID, Count_Quantity));
                                resetPanel();
                            }
                        }
                        else{
                            jLabelSuccessOrFail.setText("Never Change in Quantity :(");
                            JOptionPane.showMessageDialog(null, "Never Change in Quantity Try Again :(");
                        }
                    }
                    else{
                        jLabelSuccessOrFail.setText("Not Found Customer  :(");
                        JOptionPane.showMessageDialog(null, "Not Found Customer Try Again :(");
                    }
                    
                
            }
            else{
                jLabelSuccessOrFail.setText("Not Exsit Category in System :(");
                JOptionPane.showMessageDialog(null, "Not Exsit Category in System Try Again :(");
            }
        }else
        jLabelSuccessOrFail.setText("Missing Required Name of Customer ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        if(!jTextFieldName.getText().equals("")){
            if(((int)jSpinnerRemove.getNextValue()-1)>0){
                Customer c = new Customer();
                if(c.searchCustomer(jTextFieldName.getText())){
                    int NewVal=(Clothes_Count.get(jComboBoxItems.getSelectedIndex())-((int)jSpinnerRemove.getNextValue()-1));
                    if(NewVal>0){
                        Clothes_CountReturn.set(jComboBoxItems.getSelectedIndex(),((int)jSpinnerRemove.getNextValue()-1));
                        Clothes_Count.set(jComboBoxItems.getSelectedIndex(), NewVal);
                        jTextFieldAddListQuantity.setText(""+NewVal);
                    }
                    else if(NewVal==0){
                        JOptionPane.showMessageDialog(null, "Item "+jComboBoxItems.getSelectedItem()+" is Removed :(");
                        Clothes_NameRemoveReturn.add(jComboBoxItems.getSelectedItem().toString());
                        Clothes_CountRemoveReturn.add(Integer.parseInt(jTextFieldAddListQuantity.getText()));
                        jTextFieldAddListQuantity.setText("");
                        Clothes_Count.remove(jComboBoxItems.getSelectedIndex());
                        jComboBoxItems.removeItem(jComboBoxItems.getSelectedItem());
                    }
                    else{
                        jLabelSuccessOrFail.setText("Enter Number Between [ 0,"+Clothes_Count.get(jComboBoxItems.getSelectedIndex())+" ] :(");
                        JOptionPane.showMessageDialog(null, "Not Valid Enter Number Between [ 0,"+Clothes_Count.get(jComboBoxItems.getSelectedIndex())+" ] + Try Again :(");
                    }
                    
                    if(jComboBoxItems.getItemCount()==0){
                        jSpinnerRemove.setEnabled(false);
                        jComboBoxItems.setEnabled(false);
                        JOptionPane.showMessageDialog(null, "Not Found Items in your Basket Purchases :(");
                    }
                    jSpinnerRemove.setValue(0);
                    
                }else{
                    jLabelSuccessOrFail.setText("Not Found Customer  :(");
                    JOptionPane.showMessageDialog(null, "Not Found Customer Try Again :(");
                }
            }else{
                jLabelSuccessOrFail.setText("Enter Positive Number in Qunatity for Remove :(");
                JOptionPane.showMessageDialog(null, "Not valid Quantinty for Remove Positive Int Try Again :(");
            }
        }
        else
            jLabelSuccessOrFail.setText("Missing Required Name of Customer ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if(!jTextFieldName.getText().equals("")){
            Customer c = new Customer();
            if(c.searchCustomer(jTextFieldName.getText())){
                Clothes_NameRemoveReturn.add(jComboBoxItems.getSelectedItem().toString());
                Clothes_CountRemoveReturn.add(Integer.parseInt(jTextFieldAddListQuantity.getText()));
                jTextFieldAddListQuantity.setText("");
                //Clothes_CountReturn.set(jComboBoxItems.getSelectedIndex(),Clothes_Count.get(jComboBoxItems.getSelectedIndex()));
                Clothes_Count.remove(jComboBoxItems.getSelectedIndex());
                jComboBoxItems.removeItemAt(jComboBoxItems.getSelectedIndex());
            }else{
                jLabelSuccessOrFail.setText("Not Found Customer  :(");
                JOptionPane.showMessageDialog(null, "Not Found Customer Try Again :(");
            }
        }
        else
            jLabelSuccessOrFail.setText("Missing Required Name of Customer ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        setColor(jPanel4);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        getColor(jPanel4);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        setColor(jPanel6);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        getColor(jPanel6);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        setColor(jPanel8);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        getColor(jPanel8);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        // TODO add your handling code here:
        setColor(jPanel2);
    }//GEN-LAST:event_jLabel27MouseEntered

    private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
        // TODO add your handling code here:
        getColor(jPanel2);
    }//GEN-LAST:event_jLabel27MouseExited

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        // TODO add your handling code here:
        setColor(jPanel3);
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        // TODO add your handling code here:
        getColor(jPanel3);
    }//GEN-LAST:event_jLabel28MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxItems;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelSearchKey;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerRemove;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAddListQuantity;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSalary;
    // End of variables declaration//GEN-END:variables
}
