/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panels;

import fashion.store.management.system.Apparel;
import fashion.store.management.system.Category;
import fashion.store.management.system.Validation;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class SearchApparel extends javax.swing.JPanel {

    /**
     * Creates new form SearchApparel
     */
    public SearchApparel() {
        initComponents();
        jPanelWrongID.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPrice.setVisible(false);
        jPanelWrongQuantity.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelWrongType.setVisible(false);
    }
    private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSuccessOrFail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearchKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldStockID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCategoryName = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jComboBoxStatue = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLQuantity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBoxCurrentlyCategory = new javax.swing.JComboBox<>();
        jPanelWrongID = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelWrongType = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelWrongSearchKey = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelWrongPrice = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelWrongQuantity = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelWrongNotAllowed = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(105, 105, 105));

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Search For Apparel ...!");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stock ID");

        jTextFieldSearchKey.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jTextFieldSearchKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stock ID");

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category Name");

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Type");

        jTextFieldStockID.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldStockID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("price");

        jTextFieldCategoryName.setEditable(false);
        jTextFieldCategoryName.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldCategoryName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCategoryNameActionPerformed(evt);
            }
        });

        jTextFieldType.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldType.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldPrice.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Statue");

        jTextFieldQuantity.setEditable(false);
        jTextFieldQuantity.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityActionPerformed(evt);
            }
        });

        jComboBoxStatue.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxStatue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Increase","Decrease" }));
        jComboBoxStatue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatueActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Quantity");

        jTextFieldLQuantity.setEditable(false);
        jTextFieldLQuantity.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldLQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLQuantityActionPerformed(evt);
            }
        });

        jComboBoxCurrentlyCategory.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxCurrentlyCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jPanelWrongID.setBackground(new java.awt.Color(105, 105, 105));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel1.setText("Wrong Stock ID");

        javax.swing.GroupLayout jPanelWrongIDLayout = new javax.swing.GroupLayout(jPanelWrongID);
        jPanelWrongID.setLayout(jPanelWrongIDLayout);
        jPanelWrongIDLayout.setHorizontalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongIDLayout.setVerticalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13))
        );

        jPanelWrongType.setBackground(new java.awt.Color(105, 105, 105));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel8.setText("Wrong Type");

        javax.swing.GroupLayout jPanelWrongTypeLayout = new javax.swing.GroupLayout(jPanelWrongType);
        jPanelWrongType.setLayout(jPanelWrongTypeLayout);
        jPanelWrongTypeLayout.setHorizontalGroup(
            jPanelWrongTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelWrongTypeLayout.setVerticalGroup(
            jPanelWrongTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongTypeLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(13, 13, 13))
        );

        jPanelWrongSearchKey.setBackground(new java.awt.Color(105, 105, 105));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel9.setText("Wrong Search Key");

        javax.swing.GroupLayout jPanelWrongSearchKeyLayout = new javax.swing.GroupLayout(jPanelWrongSearchKey);
        jPanelWrongSearchKey.setLayout(jPanelWrongSearchKeyLayout);
        jPanelWrongSearchKeyLayout.setHorizontalGroup(
            jPanelWrongSearchKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSearchKeyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanelWrongSearchKeyLayout.setVerticalGroup(
            jPanelWrongSearchKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSearchKeyLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(13, 13, 13))
        );

        jPanelWrongPrice.setBackground(new java.awt.Color(105, 105, 105));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel12.setText("Wrong Price");

        javax.swing.GroupLayout jPanelWrongPriceLayout = new javax.swing.GroupLayout(jPanelWrongPrice);
        jPanelWrongPrice.setLayout(jPanelWrongPriceLayout);
        jPanelWrongPriceLayout.setHorizontalGroup(
            jPanelWrongPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanelWrongPriceLayout.setVerticalGroup(
            jPanelWrongPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPriceLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(13, 13, 13))
        );

        jPanelWrongQuantity.setBackground(new java.awt.Color(105, 105, 105));

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel13.setText("Wrong Quantity");

        javax.swing.GroupLayout jPanelWrongQuantityLayout = new javax.swing.GroupLayout(jPanelWrongQuantity);
        jPanelWrongQuantity.setLayout(jPanelWrongQuantityLayout);
        jPanelWrongQuantityLayout.setHorizontalGroup(
            jPanelWrongQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongQuantityLayout.setVerticalGroup(
            jPanelWrongQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongQuantityLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(13, 13, 13))
        );

        jPanelWrongNotAllowed.setBackground(new java.awt.Color(105, 105, 105));

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel16.setText("Not Allowed");

        javax.swing.GroupLayout jPanelWrongNotAllowedLayout = new javax.swing.GroupLayout(jPanelWrongNotAllowed);
        jPanelWrongNotAllowed.setLayout(jPanelWrongNotAllowedLayout);
        jPanelWrongNotAllowedLayout.setHorizontalGroup(
            jPanelWrongNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNotAllowedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanelWrongNotAllowedLayout.setVerticalGroup(
            jPanelWrongNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNotAllowedLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(13, 13, 13))
        );

        jPanel4.setBackground(new java.awt.Color(105, 105, 105));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_Shield_96px.png"))); // NOI18N
        jLabel32.setText("Remove");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel32)
                .addGap(10, 10, 10))
        );

        jPanel1.setBackground(new java.awt.Color(105, 105, 105));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Available_Updates_96px.png"))); // NOI18N
        jLabel31.setText("Update");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel31)
                .addGap(10, 10, 10))
        );

        jPanel2.setBackground(new java.awt.Color(105, 105, 105));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(0, 0, 0))
        );

        jPanel3.setBackground(new java.awt.Color(105, 105, 105));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Find_and_Replace_96px.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addGap(0, 0, 0))
        );

        jLabel29.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Search");

        jLabel30.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldStockID, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxCurrentlyCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanelWrongType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanelWrongPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanelWrongNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxStatue, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanelWrongQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelWrongSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSuccessOrFail)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jPanelWrongSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jTextFieldStockID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextFieldCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxCurrentlyCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jPanelWrongNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelWrongType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelWrongPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldLQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxStatue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(2, 2, 2))))
                    .addComponent(jPanelWrongQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void setPanel(Apparel a)
    {
        jTextFieldCategoryName.setText(""+a.getNameofCategory());
        jTextFieldLQuantity.setText(""+a.getQuantity());
        jTextFieldPrice.setText(""+a.getPrice());
        jTextFieldStockID.setText(""+a.getStockID());
        jTextFieldType.setText(""+a.getType());
        ArrayList<String> Current = new Category().CurrentlyCategory();
            for(int i=0;i<Current.size();i++)
                jComboBoxCurrentlyCategory.addItem(Current.get(i));
            jComboBoxCurrentlyCategory.setSelectedItem(jTextFieldCategoryName.getText());
        
    }
    private void resetPanel()
    {
        jTextFieldCategoryName.setText("");
        jTextFieldLQuantity.setText("");
        jTextFieldPrice.setText("");
        jTextFieldStockID.setText("");
        jTextFieldType.setText("");
        jComboBoxStatue.setSelectedIndex(0);
        jTextFieldQuantity.setText("");
        jComboBoxStatue.setEditable(false);
        jTextFieldQuantity.setEditable(false);
        jComboBoxCurrentlyCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jPanelWrongID.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPrice.setVisible(false);
        jPanelWrongQuantity.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelWrongType.setVisible(false);
    }
    private void jTextFieldCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCategoryNameActionPerformed

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFieldQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantityActionPerformed

    private void jTextFieldLQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLQuantityActionPerformed

    private void jComboBoxStatueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatueActionPerformed

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        
        jPanelWrongID.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPrice.setVisible(false);
        jPanelWrongQuantity.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelWrongType.setVisible(false);
        if(new Validation().checkID(jTextFieldSearchKey.getText())){
            if(!jTextFieldSearchKey.getText().equals("")){
                Apparel a = new Apparel();
                if(a.removeApparel(Integer.parseInt(jTextFieldSearchKey.getText()))){
                    resetPanel();
                    jLabelSuccessOrFail.setText("Removed Successfully ...! :)");
                }else{
                    jLabelSuccessOrFail.setText("Failed Removed ...! :(");
                    JOptionPane.showMessageDialog(null, "Not Found ID Apparel ,Failed Update...!\n Try Again :(");
                    resetPanel();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid Stock ID Try Again :(\nHint: Stock ID Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }
        else
        jLabelSuccessOrFail.setText("Missing Required ID Apparel ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        
        jPanelWrongID.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPrice.setVisible(false);
        jPanelWrongQuantity.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelWrongType.setVisible(false);
        
        if(new Validation().checkID(jTextFieldSearchKey.getText())){
            if(!jTextFieldSearchKey.getText().equals("")){
                Apparel a = new Apparel();
                if(a.removeApparel(Integer.parseInt(jTextFieldSearchKey.getText()))){
                    resetPanel();
                    jLabelSuccessOrFail.setText("Removed Successfully ...! :)");
                }else{
                    jLabelSuccessOrFail.setText("Failed Removed ...! :(");
                    JOptionPane.showMessageDialog(null, "Not Found ID Apparel ,Failed Update...!\n Try Again :(");
                    resetPanel();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid Stock ID Try Again :(\nHint: Stock ID Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }
        else
        jLabelSuccessOrFail.setText("Missing Required ID Apparel ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        jPanelWrongID.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPrice.setVisible(false);
        jPanelWrongQuantity.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelWrongType.setVisible(false);
        
        if(!jTextFieldSearchKey.getText().equals("")&&!jTextFieldCategoryName.getText().equals("")&&!jTextFieldPrice.getText().equals("")
           &&!jTextFieldQuantity.getText().equals("")&&!jTextFieldStockID.getText().equals("")&&!jTextFieldType.getText().equals(""))
        {
            Validation v = new Validation();
            if(v.checkID(jTextFieldSearchKey.getText())){
                if(v.checkID(jTextFieldStockID.getText())){
                    if(v.checkName(jTextFieldType.getText())){
                        if(v.checkPrice(jTextFieldPrice.getText())){
                            if(v.checkPrice(jTextFieldQuantity.getText())){
                                Apparel a = new Apparel();
                                if(!jTextFieldStockID.getText().equals(jTextFieldSearchKey.getText())){
                                    if(!a.Dublicate(Integer.parseInt(jTextFieldStockID.getText()))){
                                        a.setNameofCategory(jComboBoxCurrentlyCategory.getSelectedItem().toString());
                                        a.setPrice(Double.parseDouble(jTextFieldPrice.getText()));
                                        if(jComboBoxStatue.getSelectedIndex()==0)
                                            a.setQuantity(Integer.parseInt(jTextFieldQuantity.getText())+Integer.parseInt(jTextFieldLQuantity.getText()));
                                        else
                                             a.setQuantity(Integer.parseInt(jTextFieldLQuantity.getText())-(Integer.parseInt(jTextFieldQuantity.getText())));
                                        a.setStockID(Integer.parseInt(jTextFieldStockID.getText()));
                                        a.setType(jTextFieldType.getText());
                                        if(a.editInApparel(Integer.parseInt(jTextFieldSearchKey.getText()))){
                                            jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                            resetPanel();
                                        }
                                        else{
                                            jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                            JOptionPane.showMessageDialog(null, "Not Found ID Apparel ,Failed Update...!\n Try Again :(");
                                            resetPanel();
                                        }
                                    }
                                    else{
                                        jLabelSuccessOrFail.setText("Not Allowed New Stock ID :(");
                                        jPanelWrongNotAllowed.setVisible(true);
                                        JOptionPane.showMessageDialog(null, "Not Allowed Stock ID , Stock ID is Reserved...!\n Try Again :(");
                                    }
                                }
                                else{
                                    a.setNameofCategory(jComboBoxCurrentlyCategory.getSelectedItem().toString());
                                        a.setPrice(Double.parseDouble(jTextFieldPrice.getText()));
                                        if(jComboBoxStatue.getSelectedIndex()==0)
                                            a.setQuantity(Integer.parseInt(jTextFieldQuantity.getText())+Integer.parseInt(jTextFieldLQuantity.getText()));
                                        else
                                             a.setQuantity(Integer.parseInt(jTextFieldLQuantity.getText())-(Integer.parseInt(jTextFieldQuantity.getText())));
                                        a.setStockID(Integer.parseInt(jTextFieldStockID.getText()));
                                        a.setType(jTextFieldType.getText());
                                        if(a.editInApparel(Integer.parseInt(jTextFieldSearchKey.getText()))){
                                            jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                            resetPanel();
                                        }
                                        else{
                                            jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                            JOptionPane.showMessageDialog(null, "Not Found ID Apparel ,Failed Update...!\n Try Again :(");
                                            resetPanel();
                                        }
                                }
                                }
                            else{
                                JOptionPane.showMessageDialog(null, "Not Valid Quantity Try Again :(");
                                jPanelWrongQuantity.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Not valid Price Try Again :(\nHint: Price should Positive Int .. ;)");
                            jPanelWrongPrice.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid Type Try Again :(");
                        jPanelWrongType.setVisible(true);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                    jPanelWrongID.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid Stock ID Try Again :(\nHint: Stock ID Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }else
        jLabelSuccessOrFail.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jPanelWrongID.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPrice.setVisible(false);
        jPanelWrongQuantity.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelWrongType.setVisible(false);
        
        if(!jTextFieldSearchKey.getText().equals("")&&!jTextFieldCategoryName.getText().equals("")&&!jTextFieldPrice.getText().equals("")
           &&!jTextFieldQuantity.getText().equals("")&&!jTextFieldStockID.getText().equals("")&&!jTextFieldType.getText().equals(""))
        {
            Validation v = new Validation();
            if(v.checkID(jTextFieldSearchKey.getText())){
                if(v.checkID(jTextFieldStockID.getText())){
                    if(v.checkName(jTextFieldType.getText())){
                        if(v.checkPrice(jTextFieldPrice.getText())){
                            if(v.checkPrice(jTextFieldQuantity.getText())){
                                Apparel a = new Apparel();
                                if(!jTextFieldStockID.getText().equals(jTextFieldSearchKey.getText())){
                                    if(!a.Dublicate(Integer.parseInt(jTextFieldStockID.getText()))){
                                        a.setNameofCategory(jComboBoxCurrentlyCategory.getSelectedItem().toString());
                                        a.setPrice(Double.parseDouble(jTextFieldPrice.getText()));
                                        if(jComboBoxStatue.getSelectedIndex()==0)
                                            a.setQuantity(Integer.parseInt(jTextFieldQuantity.getText())+Integer.parseInt(jTextFieldLQuantity.getText()));
                                        else
                                             a.setQuantity(Integer.parseInt(jTextFieldLQuantity.getText())-(Integer.parseInt(jTextFieldQuantity.getText())));
                                        a.setStockID(Integer.parseInt(jTextFieldStockID.getText()));
                                        a.setType(jTextFieldType.getText());
                                        if(a.editInApparel(Integer.parseInt(jTextFieldSearchKey.getText()))){
                                            jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                            resetPanel();
                                        }
                                        else{
                                            jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                            JOptionPane.showMessageDialog(null, "Not Found ID Apparel ,Failed Update...!\n Try Again :(");
                                            resetPanel();
                                        }
                                    }
                                    else{
                                        jLabelSuccessOrFail.setText("Not Allowed New Stock ID :(");
                                        jPanelWrongNotAllowed.setVisible(true);
                                        JOptionPane.showMessageDialog(null, "Not Allowed Stock ID , Stock ID is Reserved...!\n Try Again :(");
                                    }
                                }
                                else{
                                        a.setNameofCategory(jComboBoxCurrentlyCategory.getSelectedItem().toString());
                                        a.setPrice(Double.parseDouble(jTextFieldPrice.getText()));
                                        if(jComboBoxStatue.getSelectedIndex()==0)
                                            a.setQuantity(Integer.parseInt(jTextFieldQuantity.getText())+Integer.parseInt(jTextFieldLQuantity.getText()));
                                        else
                                             a.setQuantity(Integer.parseInt(jTextFieldLQuantity.getText())-(Integer.parseInt(jTextFieldQuantity.getText())));
                                        a.setStockID(Integer.parseInt(jTextFieldStockID.getText()));
                                        a.setType(jTextFieldType.getText());
                                        if(a.editInApparel(Integer.parseInt(jTextFieldSearchKey.getText()))){
                                            jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                            resetPanel();
                                        }
                                        else{
                                            jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                            JOptionPane.showMessageDialog(null, "Not Found ID Apparel ,Failed Update...!\n Try Again :(");
                                            resetPanel();
                                        }
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Not Valid Quantity Try Again :(");
                                jPanelWrongQuantity.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Not valid Price Try Again :(\nHint: Price should Positive Int .. ;)");
                            jPanelWrongPrice.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid Type Try Again :(");
                        jPanelWrongType.setVisible(true);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                    jPanelWrongID.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid Stock ID Try Again :(\nHint: Stock ID Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }else
        jLabelSuccessOrFail.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        jLabelSuccessOrFail.setText("Search For Apparel ...!");
        jTextFieldSearchKey.setText("");
        resetPanel();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        resetPanel();
        if(!jTextFieldSearchKey.getText().equals("")){
            if(new Validation().checkID(jTextFieldSearchKey.getText())){
                Apparel a = new Apparel();
                a=a.getApparel(Integer.parseInt(jTextFieldSearchKey.getText()));
                if(a!=null){
                    setPanel(a);
                    jLabelSuccessOrFail.setText("Founded Apparel :)");
                    jTextFieldQuantity.setEditable(true);

                }
                else{
                    jLabelSuccessOrFail.setText("Not Found :(");
                    JOptionPane.showMessageDialog(null, "Not Found Try Again :(");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid Stock ID Try Again :(\nHint: Stock ID Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }

        }
        else
        jLabelSuccessOrFail.setText("Missing Required ID Apparel ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        // TODO add your handling code here:
        setColor(jPanel4);
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        // TODO add your handling code here:
        getColor(jPanel4);
    }//GEN-LAST:event_jLabel32MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        setColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        getColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        // TODO add your handling code here:
        setColor(jPanel2);
    }//GEN-LAST:event_jLabel27MouseEntered

    private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
        // TODO add your handling code here:
        getColor(jPanel2);
    }//GEN-LAST:event_jLabel27MouseExited

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        // TODO add your handling code here:
        setColor(jPanel3);
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        // TODO add your handling code here:
        getColor(jPanel3);
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        // TODO add your handling code here:
        setColor(jPanel1);
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        // TODO add your handling code here:
        getColor(jPanel1);
    }//GEN-LAST:event_jLabel31MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        setColor(jPanel1);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        getColor(jPanel1);
    }//GEN-LAST:event_jPanel1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCurrentlyCategory;
    private javax.swing.JComboBox<String> jComboBoxStatue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelWrongID;
    private javax.swing.JPanel jPanelWrongNotAllowed;
    private javax.swing.JPanel jPanelWrongPrice;
    private javax.swing.JPanel jPanelWrongQuantity;
    private javax.swing.JPanel jPanelWrongSearchKey;
    private javax.swing.JPanel jPanelWrongType;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCategoryName;
    private javax.swing.JTextField jTextFieldLQuantity;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldSearchKey;
    private javax.swing.JTextField jTextFieldStockID;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
