/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panels;

import fashion.store.management.system.Admin;
import fashion.store.management.system.Validation;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class SearchAdmin extends javax.swing.JPanel {

    /**
     * Creates new form SearchAdmin
     */
    public SearchAdmin() {
        initComponents();
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
    }
    private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSuccessOrFail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearchKey = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldPass = new javax.swing.JTextField();
        jPanelWrongID = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelWrongName = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelWrongUserName = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelWrongEmail = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelWrongPass = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelWrongPhoneNo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelWrongSearchKey = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelWrongNotAllowed = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(105, 105, 105));

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Search For Admin ...!");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Admin ");

        jTextFieldSearchKey.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jTextFieldSearchKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldEmail.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");

        jTextFieldPhoneNo.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldPhoneNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        jComboBoxGender.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Famele" }));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Name");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone No");

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");

        jTextFieldID.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldName.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldUserName.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldPass.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPassActionPerformed(evt);
            }
        });

        jPanelWrongID.setBackground(new java.awt.Color(105, 105, 105));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel1.setText("Wrong ID");

        javax.swing.GroupLayout jPanelWrongIDLayout = new javax.swing.GroupLayout(jPanelWrongID);
        jPanelWrongID.setLayout(jPanelWrongIDLayout);
        jPanelWrongIDLayout.setHorizontalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelWrongIDLayout.setVerticalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13))
        );

        jPanelWrongName.setBackground(new java.awt.Color(105, 105, 105));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel10.setText("Wrong Name");

        javax.swing.GroupLayout jPanelWrongNameLayout = new javax.swing.GroupLayout(jPanelWrongName);
        jPanelWrongName.setLayout(jPanelWrongNameLayout);
        jPanelWrongNameLayout.setHorizontalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanelWrongNameLayout.setVerticalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNameLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(13, 13, 13))
        );

        jPanelWrongUserName.setBackground(new java.awt.Color(105, 105, 105));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel11.setText("Wrong User Name");

        javax.swing.GroupLayout jPanelWrongUserNameLayout = new javax.swing.GroupLayout(jPanelWrongUserName);
        jPanelWrongUserName.setLayout(jPanelWrongUserNameLayout);
        jPanelWrongUserNameLayout.setHorizontalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
        );
        jPanelWrongUserNameLayout.setVerticalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserNameLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(13, 13, 13))
        );

        jPanelWrongEmail.setBackground(new java.awt.Color(105, 105, 105));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel12.setText("Wrong E-Mail");

        javax.swing.GroupLayout jPanelWrongEmailLayout = new javax.swing.GroupLayout(jPanelWrongEmail);
        jPanelWrongEmail.setLayout(jPanelWrongEmailLayout);
        jPanelWrongEmailLayout.setHorizontalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelWrongEmailLayout.setVerticalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmailLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(13, 13, 13))
        );

        jPanelWrongPass.setBackground(new java.awt.Color(105, 105, 105));

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel13.setText("Wrong Pass");

        javax.swing.GroupLayout jPanelWrongPassLayout = new javax.swing.GroupLayout(jPanelWrongPass);
        jPanelWrongPass.setLayout(jPanelWrongPassLayout);
        jPanelWrongPassLayout.setHorizontalGroup(
            jPanelWrongPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanelWrongPassLayout.setVerticalGroup(
            jPanelWrongPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPassLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(13, 13, 13))
        );

        jPanelWrongPhoneNo.setBackground(new java.awt.Color(105, 105, 105));

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel14.setText("Wrong Phone No");

        javax.swing.GroupLayout jPanelWrongPhoneNoLayout = new javax.swing.GroupLayout(jPanelWrongPhoneNo);
        jPanelWrongPhoneNo.setLayout(jPanelWrongPhoneNoLayout);
        jPanelWrongPhoneNoLayout.setHorizontalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongPhoneNoLayout.setVerticalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(13, 13, 13))
        );

        jPanelWrongSearchKey.setBackground(new java.awt.Color(105, 105, 105));

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel15.setText("Wrong Search Key");

        javax.swing.GroupLayout jPanelWrongSearchKeyLayout = new javax.swing.GroupLayout(jPanelWrongSearchKey);
        jPanelWrongSearchKey.setLayout(jPanelWrongSearchKeyLayout);
        jPanelWrongSearchKeyLayout.setHorizontalGroup(
            jPanelWrongSearchKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSearchKeyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
        );
        jPanelWrongSearchKeyLayout.setVerticalGroup(
            jPanelWrongSearchKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSearchKeyLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(13, 13, 13))
        );

        jPanelWrongNotAllowed.setBackground(new java.awt.Color(105, 105, 105));

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel16.setText("Not Allowed");

        javax.swing.GroupLayout jPanelWrongNotAllowedLayout = new javax.swing.GroupLayout(jPanelWrongNotAllowed);
        jPanelWrongNotAllowed.setLayout(jPanelWrongNotAllowedLayout);
        jPanelWrongNotAllowedLayout.setHorizontalGroup(
            jPanelWrongNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNotAllowedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanelWrongNotAllowedLayout.setVerticalGroup(
            jPanelWrongNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNotAllowedLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(13, 13, 13))
        );

        jPanel4.setBackground(new java.awt.Color(105, 105, 105));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_Shield_96px.png"))); // NOI18N
        jLabel32.setText("Remove");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel32)
                .addGap(10, 10, 10))
        );

        jPanel1.setBackground(new java.awt.Color(105, 105, 105));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Available_Updates_96px.png"))); // NOI18N
        jLabel31.setText("Update");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel31)
                .addGap(10, 10, 10))
        );

        jPanel2.setBackground(new java.awt.Color(105, 105, 105));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(0, 0, 0))
        );

        jPanel3.setBackground(new java.awt.Color(105, 105, 105));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Find_and_Replace_96px.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addGap(0, 0, 0))
        );

        jLabel29.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Search");

        jLabel30.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(201, 201, 201)
                                            .addComponent(jPanelWrongSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUserName)
                                    .addComponent(jTextFieldEmail)
                                    .addComponent(jTextFieldPhoneNo)
                                    .addComponent(jTextFieldPass)
                                    .addComponent(jTextFieldID))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelWrongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelWrongNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSuccessOrFail)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jPanelWrongSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jPanelWrongNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(20, 20, 20)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel4)
                                                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(jPanelWrongName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jPanelWrongUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanelWrongPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed
    private void resetPanel()
    {
        jTextFieldEmail.setText("");
        jTextFieldID.setText("");
        jTextFieldName.setText("");
        jTextFieldPass.setText("");
        jTextFieldPhoneNo.setText("");
        jTextFieldUserName.setText("");
        jComboBoxGender.setSelectedIndex(0);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
    }
    private void jTextFieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPassActionPerformed

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        if(!jTextFieldSearchKey.getText().equals("")){
            if(new Validation().checkID(jTextFieldSearchKey.getText())){
                Admin a = new Admin();
                if(a.removeAdmin(Integer.parseInt(jTextFieldSearchKey.getText()))){
                    resetPanel();
                    jLabelSuccessOrFail.setText("Removed Successfully ...! :)");
                }else{
                        jLabelSuccessOrFail.setText("Failed Removed ...! :(");
                        JOptionPane.showMessageDialog(null, "Not Found ID Admin ,Failed Update...!\n Try Again :(");
                        resetPanel();
                    }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Admin Try Again :(\nHint: ID Admin Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }
        else
            jLabelSuccessOrFail.setText("Missing Required ID Admin ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        if(!jTextFieldSearchKey.getText().equals("")){
            if(new Validation().checkID(jTextFieldSearchKey.getText())){
                Admin a = new Admin();
                if(a.removeAdmin(Integer.parseInt(jTextFieldSearchKey.getText()))){
                    resetPanel();
                    jLabelSuccessOrFail.setText("Removed Successfully ...! :)");
                }else{
                        jLabelSuccessOrFail.setText("Failed Removed ...! :(");
                        JOptionPane.showMessageDialog(null, "Not Found ID Admin ,Failed Update...!\n Try Again :(");
                        resetPanel();
                    }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Admin Try Again :(\nHint: ID Admin Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }
        else
            jLabelSuccessOrFail.setText("Missing Required ID Admin ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        
        if(!jTextFieldSearchKey.getText().equals("")&&!jTextFieldEmail.getText().equals("")&&!jTextFieldID.getText().equals("")&&
                !jTextFieldPhoneNo.getText().equals("")&&!jTextFieldPass.getText().equals("")&&!jTextFieldName.getText().equals("")&&
                !jTextFieldUserName.getText().equals(""))
        {
             Validation v = new Validation();
            //Start Validation
            if(v.checkID(jTextFieldSearchKey.getText())){
                if(v.checkID(jTextFieldID.getText())){
                    if(v.checkName(jTextFieldName.getText())){
                        if(v.checkName(jTextFieldUserName.getText())){
                            if(v.checkEmail(jTextFieldEmail.getText())){
                                if(v.checkPass(jTextFieldPass.getText())){
                                        if(v.checkPhoneNo(jTextFieldPhoneNo.getText())){
                                            if(!jTextFieldID.getText().equals(jTextFieldSearchKey.getText())){
                                                if(!new Admin().Dublicate(Integer.parseInt(jTextFieldID.getText()))){
                                                // Function 
                                                    Admin a = new Admin(Integer.parseInt(jTextFieldID.getText()),jTextFieldName.getText(),jTextFieldUserName.getText(),jTextFieldPass.getText()
                                                                    ,jComboBoxGender.getSelectedItem().toString(),jTextFieldPhoneNo.getText(),jTextFieldEmail.getText());
                                                    if(a.editInAdmin(Integer.parseInt(jTextFieldSearchKey.getText()))){
                                                        jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                        resetPanel();
                                                    }
                                                    else{
                                                        jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                                        JOptionPane.showMessageDialog(null, "Not Found ID Admin ,Failed Update...!\n Try Again :(");
                                                        resetPanel();
                                                    }// Start Elses Validation
                                                }
                                                else{
                                                        jLabelSuccessOrFail.setText("Not Allowed New ID Admin :(");
                                                        jPanelWrongNotAllowed.setVisible(true);
                                                        JOptionPane.showMessageDialog(null, "Not Allowed ID Admin , ID Admin is Reserved...!\n Try Again :(");
                                                    }
                                            }
                                            else{
                                                Admin a = new Admin(Integer.parseInt(jTextFieldID.getText()),jTextFieldName.getText(),jTextFieldUserName.getText(),jTextFieldPass.getText()
                                                                    ,jComboBoxGender.getSelectedItem().toString(),jTextFieldPhoneNo.getText(),jTextFieldEmail.getText());
                                                if(a.editInAdmin(Integer.parseInt(jTextFieldSearchKey.getText()))){
                                                    jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                    resetPanel();
                                                }
                                                else{
                                                    jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                                    JOptionPane.showMessageDialog(null, "Not Found ID Admin ,Failed Update...!\n Try Again :(");
                                                    resetPanel();
                                                }// Start Elses Validation
                                            }
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(null, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                                            jPanelWrongPhoneNo.setVisible(true);
                                        }
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                                    jPanelWrongPass.setVisible(true);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Not valid Input for Email Try Again :(");
                                jPanelWrongEmail.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Not valid User Name Try Again :(");
                            jPanelWrongUserName.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid Name Try Again :(");
                        jPanelWrongName.setVisible(true);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                    jPanelWrongID.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Admin Try Again :(\nHint: ID Admin Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }else
            jLabelSuccessOrFail.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongNotAllowed.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        
        if(!jTextFieldSearchKey.getText().equals("")&&!jTextFieldEmail.getText().equals("")&&!jTextFieldID.getText().equals("")&&
                !jTextFieldPhoneNo.getText().equals("")&&!jTextFieldPass.getText().equals("")&&!jTextFieldName.getText().equals("")&&
                !jTextFieldUserName.getText().equals(""))
        {
             Validation v = new Validation();
            //Start Validation
            if(v.checkID(jTextFieldSearchKey.getText())){
                if(v.checkID(jTextFieldID.getText())){
                    if(v.checkName(jTextFieldName.getText())){
                        if(v.checkName(jTextFieldUserName.getText())){
                            if(v.checkEmail(jTextFieldEmail.getText())){
                                if(v.checkPass(jTextFieldPass.getText())){
                                        if(v.checkPhoneNo(jTextFieldPhoneNo.getText())){
                                            if(!jTextFieldID.getText().equals(jTextFieldSearchKey.getText())){
                                                if(!new Admin().Dublicate(Integer.parseInt(jTextFieldID.getText()))){
                                                // Function 
                                                Admin a = new Admin(Integer.parseInt(jTextFieldID.getText()),jTextFieldName.getText(),jTextFieldUserName.getText(),jTextFieldPass.getText()
                                                                    ,jComboBoxGender.getSelectedItem().toString(),jTextFieldPhoneNo.getText(),jTextFieldEmail.getText());
                                                if(a.editInAdmin(Integer.parseInt(jTextFieldSearchKey.getText()))){
                                                    jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                    resetPanel();
                                                }
                                                else{
                                                    jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                                    JOptionPane.showMessageDialog(null, "Not Found ID Admin ,Failed Update...!\n Try Again :(");
                                                    resetPanel();
                                                }// Start Elses Validation
                                                }
                                                else{
                                                        jLabelSuccessOrFail.setText("Not Allowed New ID Admin :(");
                                                        jPanelWrongNotAllowed.setVisible(true);
                                                        JOptionPane.showMessageDialog(null, "Not Allowed ID Admin , ID Admin is Reserved...!\n Try Again :(");
                                                    }
                                            }
                                            else{
                                                Admin a = new Admin(Integer.parseInt(jTextFieldID.getText()),jTextFieldName.getText(),jTextFieldUserName.getText(),jTextFieldPass.getText()
                                                                    ,jComboBoxGender.getSelectedItem().toString(),jTextFieldPhoneNo.getText(),jTextFieldEmail.getText());
                                                if(a.editInAdmin(Integer.parseInt(jTextFieldSearchKey.getText()))){
                                                    jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                    resetPanel();
                                                }
                                                else{
                                                    jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                                    JOptionPane.showMessageDialog(null, "Not Found ID Admin ,Failed Update...!\n Try Again :(");
                                                    resetPanel();
                                                }// Start Elses Validation
                                            }
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(null, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                                            jPanelWrongPhoneNo.setVisible(true);
                                        }
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                                    jPanelWrongPass.setVisible(true);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Not valid Input for Email Try Again :(");
                                jPanelWrongEmail.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Not valid User Name Try Again :(");
                            jPanelWrongUserName.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid Name Try Again :(");
                        jPanelWrongName.setVisible(true);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                    jPanelWrongID.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Admin Try Again :(\nHint: ID Admin Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }else
            jLabelSuccessOrFail.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        jLabelSuccessOrFail.setText("Search For Admin ...!");
        jTextFieldSearchKey.setText("");
        resetPanel();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        
        resetPanel();
        if(!jTextFieldSearchKey.getText().equals("")){
            if(new Validation().checkID(jTextFieldSearchKey.getText())){
                Admin a = new Admin();
                a=a.getAdmin(Integer.parseInt(jTextFieldSearchKey.getText()));
                if(a!=null){
                    setPanel(a);
                    jLabelSuccessOrFail.setText("Founded Admin :)");
                }
                else{
                    jLabelSuccessOrFail.setText("Not Found :(");
                    JOptionPane.showMessageDialog(null, "Not Found Try Again :(");
              }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Admin Try Again :(\nHint: ID Admin Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
            
        }
        else
            jLabelSuccessOrFail.setText("Missing Required ID Admin ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        // TODO add your handling code here:
        setColor(jPanel1);
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        // TODO add your handling code here:
        getColor(jPanel1);
    }//GEN-LAST:event_jLabel31MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        setColor(jPanel1);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        getColor(jPanel1);
    }//GEN-LAST:event_jPanel1MouseExited

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        // TODO add your handling code here:
        setColor(jPanel2);
    }//GEN-LAST:event_jLabel27MouseEntered

    private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
        // TODO add your handling code here:
        getColor(jPanel2);
    }//GEN-LAST:event_jLabel27MouseExited

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        // TODO add your handling code here:
        setColor(jPanel3);
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        // TODO add your handling code here:
        getColor(jPanel3);
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        // TODO add your handling code here:
        setColor(jPanel4);
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        // TODO add your handling code here:
        getColor(jPanel4);
    }//GEN-LAST:event_jLabel32MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        setColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        getColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseExited
    private void setPanel(Admin a){
        jTextFieldEmail.setText(""+a.getEmail());
        jTextFieldID.setText(""+a.getID());
        jTextFieldName.setText(""+a.getName());
        jTextFieldPhoneNo.setText(""+a.getPhoneNo());
        jTextFieldPass.setText(""+a.getPassword());
        jTextFieldUserName.setText(""+a.getUserName());
        jComboBoxGender.setSelectedItem(a.getGender());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelWrongEmail;
    private javax.swing.JPanel jPanelWrongID;
    private javax.swing.JPanel jPanelWrongName;
    private javax.swing.JPanel jPanelWrongNotAllowed;
    private javax.swing.JPanel jPanelWrongPass;
    private javax.swing.JPanel jPanelWrongPhoneNo;
    private javax.swing.JPanel jPanelWrongSearchKey;
    private javax.swing.JPanel jPanelWrongUserName;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldSearchKey;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
